package com.want.srm.webservice.zrfcqqt005;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZRFCQQT005", targetNamespace = "http://www.example.org/ZRFCQQT005/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZRFCQQT005 {


    /**
     * 
     * @param itEKES
     * @param iEBELN
     */
    @WebMethod(operationName = "ZRFCQQT005", action = "http://www.example.org/ZRFCQQT005/ZRFCQQT005")
    @RequestWrapper(localName = "ZRFCQQT005", targetNamespace = "http://www.example.org/ZRFCQQT005/", className = "org.example.zrfcqqt005.ZRFCQQT005_Type")
    @ResponseWrapper(localName = "ZRFCQQT005Response", targetNamespace = "http://www.example.org/ZRFCQQT005/", className = "org.example.zrfcqqt005.ZRFCQQT005Response")
    public void zrfcqqt005(
        @WebParam(name = "I_EBELN", targetNamespace = "")
        String iEBELN,
        @WebParam(name = "IT_EKES", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<List<ItemType>> itEKES);

}
