package com.want.srm.webservice.zrfcqqt003;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZRFCQQT003", targetNamespace = "http://www.example.org/ZRFCQQT003/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZRFCQQT003 {


    /**
     * 
     * @param itEBELN
     * @param itSYDAT
     * @return
     *     returns java.util.List<org.example.zrfcqqt003.ItemType>
     */
    @WebMethod(operationName = "ZRCQQT003", action = "http://www.example.org/ZRFCQQT003/ZRCQQT003")
    @WebResult(name = "OT_OUTPUT", targetNamespace = "")
    @RequestWrapper(localName = "ZRCQQT003", targetNamespace = "http://www.example.org/ZRFCQQT003/", className = "org.example.zrfcqqt003.ZRCQQT003")
    @ResponseWrapper(localName = "ZRCQQT003Response", targetNamespace = "http://www.example.org/ZRFCQQT003/", className = "org.example.zrfcqqt003.ZRCQQT003Response")
    public List<ItemType> zrcqqt003(
        @WebParam(name = "IT_EBELN", targetNamespace = "")
        List<ITEBELNType> itEBELN,
        @WebParam(name = "IT_SYDAT", targetNamespace = "")
        List<ITSYDATType> itSYDAT);

}
