
package com.want.srm.webservice.si_o_zrfcsrm017;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_O_ZRFCSRM017", targetNamespace = "http://pi.want-want.com/ZRFCSRM017/Sender_Syn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIOZRFCSRM017 {


    /**
     * 
     * @param mtZRFCSRM017REQ
     * @return
     *     returns si_o_zrfcsrm017.si_o_zrfcsrm017.DTZRFCSRM017RES
     */
    @WebMethod(operationName = "SI_O_ZRFCSRM017", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZRFCSRM017_RES", targetNamespace = "http://pi.want-want.com/ZRFCSRM017/Sender_Syn", partName = "MT_ZRFCSRM017_RES")
    public DTZRFCSRM017RES siOZRFCSRM017(
        @WebParam(name = "MT_ZRFCSRM017_REQ", targetNamespace = "http://pi.want-want.com/ZRFCSRM017/Sender_Syn", partName = "MT_ZRFCSRM017_REQ")
        DTZRFCSRM017REQ mtZRFCSRM017REQ);

}
