package com.want.srm.webservice.si_o_zrfc_catch_acc_inf;

import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

import com.want.srm.utils.PropertiesUtil;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_O_ZRFC_CATCH_ACC_INFService", targetNamespace = "http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", wsdlLocation = "http://epdev.want-want.com:50000/dir/wsdl?p=sa/1f0dba43cf893573a4ba9c60b2a3fc01")
@org.springframework.stereotype.Service
public class SIOZRFCCATCHACCINFService
    extends Service
{

    private final static QName SIOZRFCCATCHACCINFSERVICE_QNAME = new QName("http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", "SI_O_ZRFC_CATCH_ACC_INFService");

    private static URL getWsdlLocation(String webserviceUrl, String account, String password) {
        Authenticator.setDefault(new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(account, password.toCharArray());
            }
        });
        URL url = null;
        try {
            url = new URL(webserviceUrl);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return url;
    }

    @Autowired
    public SIOZRFCCATCHACCINFService(@Value("${si_o_zrfc_catch_acc_inf.URL}") final String webserviceUrl, @Value("${service.account}") final String account, @Value("${service.password}") final String password) {
        super(getWsdlLocation(webserviceUrl, account, password), SIOZRFCCATCHACCINFSERVICE_QNAME);
    }
    
    public SIOZRFCCATCHACCINFService(String webserviceUrl, String account, String password, WebServiceFeature... features) {
        super(getWsdlLocation(webserviceUrl, account, password), SIOZRFCCATCHACCINFSERVICE_QNAME, features);
    }

    public SIOZRFCCATCHACCINFService(URL wsdlLocation) {
        super(wsdlLocation, SIOZRFCCATCHACCINFSERVICE_QNAME);
    }

    public SIOZRFCCATCHACCINFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIOZRFCCATCHACCINFSERVICE_QNAME, features);
    }

    public SIOZRFCCATCHACCINFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOZRFCCATCHACCINFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIOZRFCCATCHACCINF
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOZRFCCATCHACCINF getHTTPPort() {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", "HTTP_Port"), SIOZRFCCATCHACCINF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOZRFCCATCHACCINF
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOZRFCCATCHACCINF getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", "HTTP_Port"), SIOZRFCCATCHACCINF.class, features);
    }

    /**
     * 
     * @return
     *     returns SIOZRFCCATCHACCINF
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOZRFCCATCHACCINF getHTTPSPort() {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", "HTTPS_Port"), SIOZRFCCATCHACCINF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOZRFCCATCHACCINF
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOZRFCCATCHACCINF getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", "HTTPS_Port"), SIOZRFCCATCHACCINF.class, features);
    }

}
