package com.want.srm.webservice.si_o_zrfc_catch_acc_inf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_O_ZRFC_CATCH_ACC_INF", targetNamespace = "http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIOZRFCCATCHACCINF {


    /**
     * 
     * @param mtZRFCCATCHACCINFREQ
     * @return
     *     returns si_o_zrfc_catch_acc_inf.si_o_zrfc_catch_acc_inf.DTZRFCCATCHACCINFRES
     */
    @WebMethod(operationName = "SI_O_ZRFC_CATCH_ACC_INF", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZRFC_CATCH_ACC_INF_RES", targetNamespace = "http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", partName = "MT_ZRFC_CATCH_ACC_INF_RES")
    public DTZRFCCATCHACCINFRES siOZRFCCATCHACCINF(
        @WebParam(name = "MT_ZRFC_CATCH_ACC_INF_REQ", targetNamespace = "http://pi.want-want.com/ZRFC_CATCH_ACC_INF/Sender_Syn", partName = "MT_ZRFC_CATCH_ACC_INF_REQ")
        DTZRFCCATCHACCINFREQ mtZRFCCATCHACCINFREQ);

}
