package com.want.srm.webservice.zrfc_get_notification_longtext;

import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

import com.want.srm.utils.PropertiesUtil;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_O_ZRFC_GET_NOTIFICATION_LONGTEXTService", targetNamespace = "http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", wsdlLocation = "http://epdev.want-want.com:50000/dir/wsdl?p=sa/69b766c6fa7737938e413e3ce9faae24")
@org.springframework.stereotype.Service
public class SIOZRFCGETNOTIFICATIONLONGTEXTService
    extends Service
{

    private final static QName SIOZRFCGETNOTIFICATIONLONGTEXTSERVICE_QNAME = new QName("http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", "SI_O_ZRFC_GET_NOTIFICATION_LONGTEXTService");

    private static URL getWsdlLocation(String webserviceUrl, String account, String password) {
        Authenticator.setDefault(new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(account, password.toCharArray());
            }
        });
        URL url = null;
        try {
            url = new URL(webserviceUrl);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return url;
    }

    @Autowired
    public SIOZRFCGETNOTIFICATIONLONGTEXTService(@Value("${zrfc_get_notification_longtext.URL}") final String webserviceUrl, @Value("${service.account}") final String account, @Value("${service.password}") final String password) {
        super(getWsdlLocation(webserviceUrl, account, password), SIOZRFCGETNOTIFICATIONLONGTEXTSERVICE_QNAME);
    }
    
    public SIOZRFCGETNOTIFICATIONLONGTEXTService(String webserviceUrl, String account, String password, WebServiceFeature... features) {
        super(getWsdlLocation(webserviceUrl, account, password), SIOZRFCGETNOTIFICATIONLONGTEXTSERVICE_QNAME, features);
    }

    public SIOZRFCGETNOTIFICATIONLONGTEXTService(URL wsdlLocation) {
        super(wsdlLocation, SIOZRFCGETNOTIFICATIONLONGTEXTSERVICE_QNAME);
    }

    public SIOZRFCGETNOTIFICATIONLONGTEXTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIOZRFCGETNOTIFICATIONLONGTEXTSERVICE_QNAME, features);
    }

    public SIOZRFCGETNOTIFICATIONLONGTEXTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOZRFCGETNOTIFICATIONLONGTEXTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIOZRFCGETNOTIFICATIONLONGTEXT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOZRFCGETNOTIFICATIONLONGTEXT getHTTPPort() {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", "HTTP_Port"), SIOZRFCGETNOTIFICATIONLONGTEXT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOZRFCGETNOTIFICATIONLONGTEXT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOZRFCGETNOTIFICATIONLONGTEXT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", "HTTP_Port"), SIOZRFCGETNOTIFICATIONLONGTEXT.class, features);
    }

    /**
     * 
     * @return
     *     returns SIOZRFCGETNOTIFICATIONLONGTEXT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOZRFCGETNOTIFICATIONLONGTEXT getHTTPSPort() {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", "HTTPS_Port"), SIOZRFCGETNOTIFICATIONLONGTEXT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOZRFCGETNOTIFICATIONLONGTEXT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOZRFCGETNOTIFICATIONLONGTEXT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", "HTTPS_Port"), SIOZRFCGETNOTIFICATIONLONGTEXT.class, features);
    }

}
