package com.want.srm.webservice.zrfc_get_notification_longtext;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_O_ZRFC_GET_NOTIFICATION_LONGTEXT", targetNamespace = "http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIOZRFCGETNOTIFICATIONLONGTEXT {


    /**
     * 
     * @param mtZRFCGETNOTIFICATIONLONGTEXTREQ
     * @return
     *     returns zrfcsrm016.zrfc_get_notification_longtext.DTZRFCGETNOTIFICATIONLONGTEXTRES
     */
    @WebMethod(operationName = "SI_O_ZRFC_GET_NOTIFICATION_LONGTEXT", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZRFC_GET_NOTIFICATION_LONGTEXT_RES", targetNamespace = "http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", partName = "MT_ZRFC_GET_NOTIFICATION_LONGTEXT_RES")
    public DTZRFCGETNOTIFICATIONLONGTEXTRES siOZRFCGETNOTIFICATIONLONGTEXT(
        @WebParam(name = "MT_ZRFC_GET_NOTIFICATION_LONGTEXT_REQ", targetNamespace = "http://pi.want-want.com/ZRFC_GET_NOTIFICATION_LONGTEXT/Sender_Syn", partName = "MT_ZRFC_GET_NOTIFICATION_LONGTEXT_REQ")
        DTZRFCGETNOTIFICATIONLONGTEXT mtZRFCGETNOTIFICATIONLONGTEXTREQ);

}
