package com.want.srm.webservice.zrfcsrm016;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_O_ZRFCSRM016", targetNamespace = "http://pi.want-want.com/ZRFCSRM016/Sender_Syn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIOZRFCSRM016 {


    /**
     * 
     * @param mtZRFCSRM016REQ
     * @return
     *     returns zrfcsrm016.zrfcsrm016.DTZRFCSRM016RES
     */
    @WebMethod(operationName = "SI_O_ZRFCSRM016", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZRFCSRM016_RES", targetNamespace = "http://pi.want-want.com/ZRFCSRM016/Sender_Syn", partName = "MT_ZRFCSRM016_RES")
    public DTZRFCSRM016RES siOZRFCSRM016(
        @WebParam(name = "MT_ZRFCSRM016_REQ", targetNamespace = "http://pi.want-want.com/ZRFCSRM016/Sender_Syn", partName = "MT_ZRFCSRM016_REQ")
        DTZRFCSRM016REQ mtZRFCSRM016REQ);

}
